### ISSUE TITLE
Update rich

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/daq-release#103]
Could we have a new version of rich in the daq repo? At least v10.9.0 is required to parse json:
https://github.com/willmcgugan/rich/releases/tag/v10.14.0

**Comment by dingp** [comment]
Sure. This will be updated in `dunedaq-v2.9.0`.

**Comment by dingp** [comment]
New version has been published to cvmfs. Will update `dunedaq-develop` and `dunedaq-v2.9.0` release configs.
