### ISSUE TITLE
Making a newer `uhal` package

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#12]
Alessandro requested to have a newer version of `uhal` as he needs a new feature which only exists since `v2.7.9`. The current version we have is for `v2.6.4`.

The upgrade will require going over the build script as well as the patching files.

**Comment by dingp** [comment]
Test cross repo issue linking...

DUNE-DAQ/daq-docker#1

**Comment by alessandrothea** [comment]
It's worth waiting for the next uhal release, where the boost python bindings are replaced by pybind11. 
This will help with our own python bindings, which we plan to base on pybind11 as well.

**Comment by dingp** [comment]
2.8.0 release is out. It now depends on [pybind11](https://github.com/pybind/pybind11), a header-only library, which is to replace boost.python. 

Making another issue for creating a UPS product of pybind11.
