### ISSUE TITLE
Preparing the deployment of DUNE DAQ spack releases to cvmfs

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#130]
This has been done. Details might be too long to be posted in an issue. I've created a wiki page (linked below) for the preparation of deployment done on two NP04 servers. 

Link to the wiki page with all the detailed steps can be found at:
[Preparing the deployment of DUNE DAQ spack releases to cvmfs](https://github.com/DUNE-DAQ/daq-release/wiki/Preparing-the-deployment-of-DUNE-DAQ-spack-releases-to-cvmfs)

I've followed the steps in the wiki page above multiple times. Once we are satisfied with the end products, this wiki page will be moved into `docs`.

**Comment by dingp** [comment]
Instructions to use the current cvmfs sandbox deployment can be found in this wiki page](https://github.com/DUNE-DAQ/daq-release/wiki/Instructions-to-use-the-spack-releases-deployed-in-cvmfs). 

Please refer to:
1. ["For a nightly release in cvmfs sandbox deployment"](https://github.com/DUNE-DAQ/daq-release/wiki/Instructions-to-use-the-spack-releases-deployed-in-cvmfs#for-a-nightly-release-in-cvmfs-sandbox-deployment) if trying this with a nightly release;
2. ["For a frozen release in cvmfs sandbox deployment"](https://github.com/DUNE-DAQ/daq-release/wiki/Instructions-to-use-the-spack-releases-deployed-in-cvmfs#for-a-frozen-release-in-cvmfs-sandbox-deployment) if trying this with a frozen release.

Note that the prebuilt pyvenv and `dbt-settings.sh, dbt-build-order.cmake` are not yet prepared/published to cvmfs. They are tracked in #132 once the spack release in the current cvmfs sandbox deployment is tested by others in the SW coordination team.

**Comment by dingp** [comment]
Link #132 to this issue, as the pre-built python virtual environment should be part of the spack release.

**Comment by dingp** [comment]
While we are waiting for the spack flavored dbt to support the latest sandbox deployment for spack releases, the following test procedure worked with the frozen release (`dunedaq-v2.10.1`) deployed in cvmfs sandbox:

1. start a CS8 docker container as shown in the instructions, but mount the `/cvmfs` directory from the host to the container;
2. setup the spack instance from the nightly release area;
3. active the frozen release's spack environment;
4. setup the latest dbt version from cvmfs, and create a work area with the release;
5. in the work area, after running `dbt-workarea-env`, unsetup all UPS products by calling `unsetup_all`;
6. load the umbrella package `spack load dunedaq@dunedaq-v2.10.1`;
7. checkout `appfwk` into the source code directory, and then run `dbt-build.py`.

The above steps essentially used all external packages from spack. 

Continuing to test the full release build by checking out all DAQ packages into `sourcecode`.

**Comment by dingp** [comment]
The spack release has a newer `cmake` (`3.21.4` vs `3.17.2`). I noticed some changes in the build log for building the whole release.

1. Instead of `[i_th/N_total]` in front of each target line, newer cmake uses `[N%]`.
2. There is a warning (included below) after the configuration about setting the `CMP0115` policy, which we might use for good practices. 
3. The installation phase also has a `[N%]` indicating the progress of installation preceding each line of targets.
4. The installation phase has lines explicitly saying `Consolidate compiler generated dependencies of target XXXX`.

```bash
Creating /scratch/dev-N22-04-02/build/sspmodules/codegen/include/sspmodules/sspcardreaderinfo to hold moo-generated plugin headers for sspmodules/sspcardreaderinfo.jsonnet since it doesn't yet exist
-- Configuring done
CMake Warning (dev) at /scratch/dev-N22-04-02/build/daq-cmake/DAQ.cmake:380 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /scratch/dev-N22-04-02/sourcecode/wibmod/src/wib.pb.cc
Call Stack (most recent call first):
  wibmod/CMakeLists.txt:24 (daq_add_library)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
```

**Comment by jcfreeman2** [comment]
I just set up a work area as per the instructions at https://github.com/DUNE-DAQ/daq-buildtools/tree/johnfreeman/issue161_spack#readme , and built each DUNE-DAQ repo as listed in `dbt-build-order.cmake` in isolation against the `N22-04-02` Spack installation. They all built without errors except for (1) `daqdemo`, which shouldn't be in that list, and (2) `fdreadoutlibs` and `dfmodules`, which both include a `TPSet.hpp` from the `trigger` package that's been modified since April 2, creating a conflict. As (1) and (2) can be easily explained as issues unrelated to the Spack installation, I'm confident that the installation plus the branch of daq-buildtools pass this test.

**Comment by dingp** [comment]
The production deployment has been published to cvmfs.

It was prepared using a SL7 container. It is forward-compatible with CS8. It contains `dunedaq-v2.10.1` and `N22-04-09` releases.

Note that the deployment prepared on CS8 is not backward compatible with SL7, because of `glibc`.

My tests with the production deployment succeeded on a SL7 node (`mu2edaq13.fnal.gov`) and a CS8 node (`np04-srv-015.cern.ch`). I tested using the space-enabled `dbt`, and created work areas based on `dunedaq-v2.10.1` and `N22-04-09`, and further built a few packages (`appfwk` etc) with `--lint` and `--unittest`.

**Comment by dingp** [comment]
A few things remaining on the list:

- [ ] add `spack-installation` symlink to `spack-0.17.1` in releases directory;
- [ ] modify `dbt` with the new pathes (replace the lines containing `sandbox`);
- [ ] update dbt  to get rid of `spack-0.17.1` in path names, but use the `spack-installation` symlink in each release directory to determine the spack installation path;
- [ ] Go through the documentation, update things accordingly, and at the bottom of the page, add a section (or a link to a separate page) on spack usage tips . It can include examples like how to view available packages, loaded packages, DAQ packages in the release etc ( `spack find, spack find --loaded -N, spack find --loaded -N | grep <dunedaq release name>` )

**Comment by dingp** [comment]
Done. Deployment has been prepared. John also tested the procedure by creating a nightly release deployment. (part of the review for PR https://github.com/DUNE-DAQ/daq-release/pull/128 has been merged.)
