### ISSUE TITLE
Adding clang to the spack instance so that linting works

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#135]
Currently, for `clang-tidy.sh` to work on C++ code, `clang` from UPS products area will need to be set up first.

We will be facing similar need when using the spack release. If there's no better way to run `clang-tidy.sh` unless `clang` is se up, we can install it in the externals spack instance. 

@jcfreeman2 Which clang version do you use for the clang-build? It might be good to have the same version deployed in cvmfs.

**Comment by dingp** [comment]
It might be better to make an additional `spack` instance, e.g. `spack-extras`, which will use `spack-externals` as upstream spack instance, and additionally, have `clang` and `gcc9` installed.

`clang` is needed for linting, and `gcc9` is needed for generating code coverage report.

**Comment by jcfreeman2** [comment]
`spack install llvm@13.0.0`

**Comment by dingp** [comment]
I am thinking about creating a `spack-extras` instance under `dunedaq` cvmfs repo. It is at the same level as `speck-externals`. 

`spack-extras` is the instance where `clang (llvm)`, `gcc9`, `lcov`, `cppcheck`, and possibly other tools can be installed.

**Comment by dingp** [comment]
Per discussion during SW Coord meeting today, we will have these extra dev tools in `speck-externals` instance.

Initially, we planned to have `clang` and `gcc9` covered by the `devtools` umbrella package, but that will conflict with our default compiler `gcc8`. 

So I will have `clang` and `gcc9` individually added to spack, without adding them to any umbrella package before we come up with a better solution.

**Comment by dingp** [comment]
`clang, gcc9, cppcheck, openssh` have been added to `speck-externals.
