### ISSUE TITLE
Remove build scripts for UPS products after spack transition 

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#136]
Remove `scripts/ups_buiild_scripts`, `cetbuildtools_scripts` etc after transition to spack in `dunedaq-v3.0.0`.

Currently release `dunedaq-v2.11.0` is planed to have both UPS and spack support, `dunedaq-v3.0.0` will be spack-only.

**Comment by dingp** [comment]
Since we will build UPS-based releases for `dunedaq-v3.0.0` as a backup to the spack-based release, this issue should be resolved post `v3.0.0`. I am changing the target release to `v3.1.0`.

**Comment by jcfreeman2** [comment]
Handled via PR #204
