### ISSUE TITLE
Auto-update package.pys to reflect new dependencies

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#139]
Last night the Spack installation based on the auto-generation of `package.py`s didn't work out-of-the-box since a couple days prior a new dependency of `ipm` on the `utilities` package had been added, and there wasn't a corresponding `depends_on("utilities")` in `ipm`'s `package.py`. It's worth investigating ways to parse `CMakeLists.txt` and possibly also `<package>Config.cmake` in order to add (or even remove) `depends_on` calls when appropriate. If we want to get sophisticated, this could even determine whether a dependency is build-only or not. During today's Software Coordination meeting, Alessandro mentioned this tool which might help: https://github.com/wjwwood/parse_cmake

**Comment by dingp** [comment]
Changed the target release to v3.1.0.

**Comment by dingp** [comment]
Will implement this check into CI jobs.

**Comment by jcfreeman2** [comment]
Things have reached a point where our software stack is large and complex enough that this could really save a lot of headaches. To elaborate a bit: while `make-release-repo.py` does in fact already make substitutions in the `package.py` templates located in `./spack-repos/dunedaq-repo-template/packages` - e.g. replacing `XVERSIONX` with the needed version or commit hash - it's still the case that a given package's dependencies are hardwired into the `package.py` file even before `make-release-repo.py` gets its hands on it. It would be very useful if `make-release-repo.py` could look at a given package's `CMakeLists.txt` and _deduce_ what dependencies were needed, automatically adding them.

**Comment by alessandrothea** [comment]
Hi, I spotted a minor issue in the new logic when playing with building the externals on mac: the search logic used to determine whether a package depends on moo, pybind, etc.. doesn't take into account whether lines are commented or not.
This results in packages like `utilities` and `detchannelmaps` to pickup an unnecessary pymoo dependency, for instance, since the include a commented call to `daq_codegen`
