### ISSUE TITLE
Investigate updating to a new gcc

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#194]
For the last 2+ years we've been using gcc v8.2.0 as the standard compiler for the build of the DUNE DAQ software stack; furthermore, our [coding guidelines](https://dune-daq-sw.readthedocs.io/en/latest/packages/styleguide/#1-c-version) require that the C++17 standard be used. At this point in time there are versions of gcc which for all intents and purposes support the C++20 standard, and it's well worth considering taking advantage of its features now that C++20 is no longer at the "bleeding edge". Other advantages such as more verbose/insightful warnings and better optimization may also be available.

**Comment by dingp** [comment]
I had the full suite of external packages and DAQ packages built with gcc12. I had to make some patches though. I will publish the built externals and release to cvmfs soon.
