### ISSUE TITLE
Documentation on how to cut a new release should be updated

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#195]
As the release coordinator for dunedaq-v3.1.0, it would be very helpful if the [documentation for how to cut a new release](https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-release/create_release/) and its associated links could be modernized. There's currently a lot of useful information in there, but the documentation is about a year old. Assumptions are still made that we're working with UPS and not Spack; furthermore it appears that some of the scripts referred to in the instructions no longer exist (e.g. `~/bin/dune-split` on oasiscfs01.fnal.gov). The more precise the instructions for release coordinators, the better.

**Comment by dingp** [comment]
A new page was created for making Spack-based release before the testing period started in the 3.1 release cycle.

https://github.com/DUNE-DAQ/daq-release/blob/develop/docs/create_release_spack.md
