### ISSUE TITLE
Preparing dunedaq-v2.2.0 "The Rise of MiniDAQapp"

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-release#20]
This is a ticket to plan and track the preparation of the next release, `v2.2.0`.

The branch `thea/prep-dunedaq-v2.2.0` branch to aggregate the changes (more suitable name welcome).

Initial shopping list (to be updated)
1. Build tools
   - [x] Enable package conflict check in UPS DUNE-DAQ/daq-buildtools#87
2. System packages
   - [x] Resolve `sqlite` conflict between `python 3.8` and `cetlib` (issue?)
   - [x] move `hdf5` from `products_dev` to `products` (is this system or external?)
   - adding clang into the externals package list in the next release
3. Externals
  **WARNING**: due to the upgrade of the some system packages (2.) **ALL** daq externals must be rebuilt.
   - ~Consolidate `pistache` (version vs hash)~
   - [x] move `zmq` to `products` and add to the externals list for default setup;
   - [x] add `clang` to the externals list;
4. Python packages
   - [x] Update moo to `v0.5.2`
5. Build, test and deploy the release. 
 - [x] DAQ packages (add tags as they become available)
  **WARNING**: due to the upgrade of the some system packages (2.) **ALL** daq packages must be rebuilt.
   |        repo       |   tag    |
   |-------------------|----------|
   | `daq-buildtools`  | `v2.0.1` |
   | `daq-cmake`       | `v1.2.3` |
   | `cmdlib`          | `v1.0.2` |
   | `restcmd` | `v1.0.3` |
   | `appfwk.git`      | `v2.1.0` |
   | `dataformats.git` | `v1.0.0` |
   | `dfmessages.git`  | `v1.0.0` |
   | `dfmodules.git`   | `v1.1.1` |
   | `trigemu.git`     | `v1.0.0` |
   | `readout.git`     | `v1.0.1` |
   | `minidaqapp.git`  | `v1.2.0` |
   | `listrev` | `v2.0.1` |
   | `ipm`   | `v1.1.0`  | 
- [x] In`thea/prep-dunedaq-v2.2.0` branch of `daq-release/config/dunedaq-v2.2.0-prep` config folder to start aggregating the ingredients
- [x] Built and made UPS packages for DAQ packages above, deployed to cvmfs;
- [x] Create release directory and deployed to cvmfs;
- [x] Update "Compiling and Running Wiki" and announce `dunedaq-v2.2.0` is available for test;
- [x] Merge  `thea/prep-dunedaq-v2.2.0` branch to `master`, tag `master` (tag `v1.2.1`), merge to `develop`;
- [x] After 24 hours, tag packages above and `daq-release` with `dunedaq-v2.2.0` tag.

 To Be Continued...

**Comment by dingp** [comment]
Adding to the list, adding `clang` into the `externals` package list in the next release.
