### ISSUE TITLE
new trace with python support

### ISSUE THREAD

**Issue by ron003** [DUNE-DAQ/daq-release#205]
new trace with python support --
compile python/tracelib.c:
gcc -g -Wall -I$TRACE_INC -o libtracelib.so -shared -fPIC tracelib.c

**Comment by plasorak** [comment]
Hi Ron, what do we need to do about this? Update Trace?

**Comment by ron003** [comment]
Yes. I need to finish release notes and send a notice on the daq integration channel.
--Ron
On Fri, 2023-01-27 at 01:03 -0800, Pierre Lasorak wrote:

Hi Ron, what do we need to do about this? Update Trace?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DUNE-2DDAQ_daq-2Drelease_issues_205-23issuecomment-2D1406204668&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=7KXkqf0bzyUQv15jBKEcHw&m=yShCl3z19o55OCu4een6m7i7siT4DbCO1raNq47wfSxLQge8MTsEmj-i51GhwvY6&s=lX0-CFVAo5xssjUCE69p0VSCx-MeoADJoHtMz6aev-M&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGH7VZQE6GGLJ3JCVJPDACDWUOFOLANCNFSM6AAAAAAQGGHO4U&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=7KXkqf0bzyUQv15jBKEcHw&m=yShCl3z19o55OCu4een6m7i7siT4DbCO1raNq47wfSxLQge8MTsEmj-i51GhwvY6&s=yQL6_DsgmBd_DOB9SqUaCt4dVp0mSCkDRPJ0L5nKsq8&e=>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


--

Ron Rechenmacher
Engineer, Tools and Advanced Computing
Fermi National Accelerator Laboratory
Batavia, IL  60510

**Comment by dingp** [comment]
This has been done.
