### ISSUE TITLE
Get consistent versions of `moo` between Spack and `dbt-pyvenv`

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#211]
Gordon Crone pointed out that his work area has `moo` version  `0.5.7` rather than the desired `0.6.3` which we've specified in the `./configs/dunedaq-develop/dunedaq-develop.yaml` file. Pengfei's noted that we still have `py-moo 0.5.7` in Spack, and this is taking precedence over the `dbt-pyvenv` `moo` library. We should update `./spack-repos/externals/packages/py-moo/package.py` so that it sets `0.6.3` rather than `0.5.7` as the version.

**Comment by dingp** [comment]
I did several things to fix the issue:

1. updated `package.py` for `py-moo` with newer version `0.6.3`;
1. moved `py-moo` and  its dependent python packages to the `dunedaq` section of release YAML, and specified the new version for `py-moo`, so `py-moo` `0.6.3` will be installed and used when building other daq packages;
1. changed [scripts/dbt-workarea-env.sh](https://github.com/DUNE-DAQ/daq-release/issues/211#diff-59915f79b3ac682714a4f23df1b6781324f0923a4692e13dd0f68b90f6c73bf4) so the python lib in the local venv takes precedence over spack installed python modules (this is on `thea/venv_setup` branch, not on develop yet).

**Comment by dingp** [comment]
The issue contains two parts: 

a. new version of moo should have been used by spack when installing DAQ packages;
b. local python modules in venv lib should have taken precedence over spack installed python packages. 

So item 1 and 2 in the previous comment fixes a, and 3&4 fixes b.

**Comment by dingp** [comment]
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/9438483/200987085-42074320-3db3-4a88-8dff-7615b2cbb6df.png">

The new nightly release `NT22-11-09` built [here](https://github.com/DUNE-DAQ/daq-release/actions/runs/3431526718) showed correct `moo` version now.
