### ISSUE TITLE
Dashboard for the single-repo CIs

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#346]
Currently, after the nightly build is complete, each DUNE DAQ repo gets individually built against the nightly as a check (see, e.g., https://github.com/DUNE-DAQ/appfwk/actions/runs/7882862207). However, there's no way to see all the results in one location, making it difficult to determine whether all single-repo CIs have passed. Three years ago as I recall a successful (but temporary) attempt was made, and the link still exists in https://github.com/DUNE-DAQ/daq-release/blob/develop/docs/ci_github_action.md . Either using the same service [https://meercode.io/](Meercode) or another one, we should investigate bringing back this dashboard.

**Comment by jcfreeman2** [comment]
Also worth pointing out: any solution should ideally not involve a monthly payment.

**Comment by andrewmogan** [comment]
The README now contains a list of repos with their pass/fail badges next to them.
