### ISSUE TITLE
checkout-daq-package.py -p is not working

### ISSUE THREAD

**Issue by ron003** [DUNE-DAQ/daq-release#356]
Seems:
-def checkout_commit(repo, commit, outdir, is_success_required):
+def checkout_commit(repo, commit, outdir, is_success_required = True):
may be needed.
I'll submit PR shortly.

**Comment by jcfreeman2** [comment]
Thanks for the PR. However, it seems like using `checkout-daq-package.py` to check out a single package and not doing a version crosscheck (the arguments needed to reproduce the error) remains broken and there are deeper issues there to be fixed (e.g., the commit has the Python `None` value, breaking the result). I'll take a look when I get a chance.
