### ISSUE TITLE
It should be an error if `make-release-repo.py` can't find an expected tag

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#366]
The motivation for this Issue is an attempted candidate build I tried to perform over the weekend, https://github.com/DUNE-DAQ/daq-release/actions/runs/8868482226. The immediate cause of that build failing is that `hsilibs` couldn't compile, but the reason for that is that `hsilibs`, despite beings listed in the relevant `release.yaml` as being `v4.1.0` _didn't yet have that tag_. Indeed, on line 433 of the output you see
```
Info: hsilibs              | v4.1.0               | b6e0904
```
...where what's noteworthy is that the commit `b6e0904` represented the head of the `production/v4` branch at the time (which aligned with `v3.1.0`, modulo some Workflow `*.yaml` changes). 

In such a situation  - i.e., there's not actually a git tag in the repo corresponding to the requested tag - `make-release-repo.py` should immediately exit with a failure. We were lucky that `hsilibs` didn't happen to compile, but this falls under the category of "Better to fail loudly than silently and unnoticed".

**Comment by andrewmogan** [comment]
Resolved as of PR #367
