### ISSUE TITLE
Provide a check_prerequisites script for checking if required system packages are installed

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#37]
Plan to develop a script for developers to check if their systems have the system packages required by the DUNE-DAQ release.

As a hint of the currently required system packages, the [DUNE-DAQ/daq-docker](https://github.com/DUNE-DAQ/daq-docker) repo contains Dockerfiles for CentOS7 and CentOS8 images which meets the requirements.

**Comment by alessandrothea** [comment]
Just a warning: the Docker images contain way more than is actually required so they're not a very good reference at the moment.

**Comment by dingp** [comment]
Created a minimalist SL7 docker image in which one can build/run the release DUNE-DAQ/daq-docker#2.

**Comment by dingp** [comment]
Looks like pointing people to the Dockerfile for the `sl7-minimal` image has been working well enough.
