### ISSUE TITLE
Add checked out source code to /cvmfs release directory

### ISSUE THREAD

**Issue by gcrone** [DUNE-DAQ/daq-release#375]
It is sometimes nice to easily see the code that a release was built from without having to find the package and checkout the specific tag/hash from git. Adding the source code that the release is built from to the /cvmfs area in a single tree with an environment variable such as `DUNE_DAQ_RELEASE_SOURCE` pointing to it could be useful for debugging.

**Comment by jcfreeman2** [comment]
Feature now available in `daq-buildtools` `v8.6.1` thanks to Andrew
