### ISSUE TITLE
Rename readout classes and repositories

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-release#379]
Note: Cannot rename readoutlibs/modules without breaking v4.X development; must make new repo. 

Proposed steps:
1. Rename `ReadoutModule` (and `ReadoutModuleConf`) to `DataHandler` (and `DataHandlerConf`) and push to nightlies - **already done**
2. Create the new `datahandlinglibs` repository by git-mirroring `readoutlibs`
3. Copy `readoutmodules` code into `datahandlinglibs`
4. In `datahandlinglibs` only: update namespace names to `datahandlinglibs`. Rename `ReadoutConcept.*` and `ReadoutModel.*` `ReadoutModulesIssues` to `DataHandling*`
5. Add `datahandlinglibs` to nightlies
6. Switch the rest of the code from `readoutlibs`/`readoutmodules` to `datahandlinglibs`. Rename `*DataLinkHandler` as `*RawDataHandler`

**Comment by jcfreeman2** [comment]
Complete; changes going in to `fddaq-v5.1.0`
