### ISSUE TITLE
Update sync-ci-track-pr-workflow-to-template.sh for v4/v5 split

### ISSUE THREAD

**Issue by andrewmogan** [DUNE-DAQ/daq-release#383]
It seems that `sync-ci-track-pr-workflow-to-template.sh` hasn't been run in a couple years, at least according to the [commit history from fdreadoutlibs](https://github.com/DUNE-DAQ/fdreadoutlibs/commits/production/v4/.github/workflows/track_new_issues.yml). This means that packages less than two years old, like `drunc` and `druncschema`, don't have a `.github/workflows` area created unless someone manually created it (as was the case for `cibmodules` where I manually copy-pasted the workflows upon creation). This also means that `sync-ci-track-pr-workflow-to-template.sh` hasn't been updated since the split between production/v4 and develop/v5. One can compare to `sync-ci-workflow-to-template.sh`, which has a `DEVLINE` argument. `sync-ci-track-pr-workflow-to-template.sh` should be similarly updated.

**Comment by jcfreeman2** [comment]
See also https://github.com/DUNE-DAQ/daq-release/issues/392 which I just filed.

**Comment by andrewmogan** [comment]
Addressed by #395
