### ISSUE TITLE
Python packages in the nightly should be installed from the head of `develop`

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#388]
For a couple of years now, DUNE DAQ Python and C++ packages have been treated differently in the nightly since C++ repos are taken from the head of `develop` whereas Python packages are taken from the tagged version that's listed in the relevant YAML file here in `daq-release`. In light of some confusion a week or two back as to why changes to `drunc`'s `develop` branch weren't appearing in the nightly, I think it would be good to actually use the `develop` branch in the nightly; there seems to be agreement on this from developers.

**Comment by andrewmogan** [comment]
Resolved with #389
