### ISSUE TITLE
Clean up obsolete scripts in `./scripts/github-ci`

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#392]
Right now, there's a lot of scripts in `./scripts/github-ci` which we don't use and/or which don't use useful tools which were developed later (e.g., `./scripts/list_packages.py`). It would be nice to review the scripts we have in there, deciding which ones we should drop, which ones we should keep, and which ones we should keep but also update. 

Changes made to satisfy this issue should be done on a feature branch with an associated PR, given the potential for disruption to our workflows.

**Comment by andrewmogan** [comment]
Addressed by #395
