### ISSUE TITLE
Automation of unit tests, linting and clang format checks

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#405]
At the v5.2 release meeting yesterday Eric mentioned the usefulness of running unit tests and clang format checks automatically. One problem I raised at the time is that the llvm package which is used for clang formatting (and linting) is several gigabytes and therefore, although on /cvmfs, not in the images in which we perform our nightly build. Having said that, there's no reason we couldn't just create a GitHub Action which runs directly on one of our self-hosted runners, sets up a work area, checks out our repos, and then runs `dbt-build --unittest --lint`, as well as `dbt-clang-format.sh`. The difficult part here would be figuring out how best to report the results, beyond just going through the full log of the output.

**Comment by andrewmogan** [comment]
Addressed by #411 and #414.
