### ISSUE TITLE
Request to update the (py-)pytest external package to version 8.3.3 for for fddaq-v5.3.0

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daq-release#406]
From what I understand, we are currently using version 7.3.2 of pytest. 

There are several features of the newer pytest that would be nice-to-have.  One is the ability to set the number of retained temporary directories.  

My suggestion to upgrade to version 8.3.3 is just to get to the latest version.  If there are reasons not to upgrade to the latest version, I can look a little harder at what new features we would like to have and determine which post-7.3.2 version is a good alternative.

**Comment by jcfreeman2** [comment]
The pytest version was bumped up to 8.3.3 for last night's nightly (further details in https://github.com/DUNE-DAQ/daq-release/pull/407).
