### ISSUE TITLE
Problem with saving the code into `$DUNE_DAQ_RELEASE_SOURCE`

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#408]
It seems as if, even when a nightly build is performed where a preferred feature branch is given, the code which gets saved into the the directory pointed to by `$DUNE_DAQ_RELEASE_SOURCE` is always code from `develop` branches. Example: recently I built a nightly, `NFDT_DEV_241107_A9`, which defaulted to the `johnfreeman/daq-deliverables_issue149_rename_session` branch where possible (https://github.com/DUNE-DAQ/daq-release/actions/runs/11731796041).

To take a specific repo: in `erskafka` I switched all instances of `DUNEDAQ_PARTITION` to `DUNEDAQ_SESSION` on that feature branch. And indeed, you can see this switch in the compiled code:
```
cd /cvmfs/dunedaq-development.opensciencegrid.org/nightly/NBT_DEV_241107_A9/spack-0.22.0/opt/spack/linux-almalinux9-x86_64/gcc-12.1.0/erskafka-NBT_DEV_241107_A9-pjgidl444z4q3o6h2gl6bnietb542bjw
find . -type f | xargs grep -l DUNEDAQ_PARTITION  # No files listed
find . -type f | xargs grep -l DUNEDAQ_SESSION     # Files listed
```
However, going to the directory pointed to by `$DUNE_DAQ_RELEASE_SOURCE`, now the `DUNEDAQ_PARTITION` reappears, consistent with what's on the `develop` rather than feature branch:
```
cd /cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT_DEV_241107_A9/sourcecode/erskafka
find . -type f | xargs grep -l DUNEDAQ_PARTITION  # Files listed
```
And other inspections will reveal that the code seen is that from the `develop` branch. E.g., more comprehensively, we can compare the test nightly to that day's regular nightly:
```
diff -rq /cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT_DEV_241107_A9/sourcecode/erskafka /cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFD_DEV_241107_A9/sourcecode/erskafka | grep -v .git
```

**Comment by andrewmogan** [comment]
Addressed by #409.
