### ISSUE TITLE
Organization of develop and nightly build releases

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#41]
This is a proposal to have a development release and nightly build releases. It is needed by Continuous Integration at least and at some point by the general DAQ developers.

1. Create `nightly` subdirectory under `releases`, in which it contains subdirectories named by weekdays (`mon, tue, wed, the, fri`); and each weekday subdirectory in itself is a release directory just a `dunedaq-v2.2.0`; however, for the `packages` directory, instead of symlinks, it contains the actual content of the `develop` version of DAQ packages.
2. Create a `develop` release under `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/releases`, which links to the latest successfully-built nightly release.

**Comment by alessandrothea** [comment]
Hi, I think it's reasonable, but I have a couple of questions

> 1. Create `nightly` subdirectory under `releases`, in which it contains subdirectories named by weekdays (`mon, tue, wed, the, fri`); and each weekday subdirectory in itself is a release directory just a `dunedaq-v2.2.0`; however, for the `packages` directory, instead of symlinks, it contains the actual content of the `develop` version of DAQ packages.

I would not mix releases and nightlies, and rather have the `nightly` folder at the same level as `releases`.
Weekly rotation sounds perfect.

> 2. Create a `develop` release under `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/releases`, which links to the latest successfully-built nightly release.

How about `nightly/last_successful` or similar? Should it be symlinked or copied, to avoid deletion if for any reason the nightly remains broken for long?

**Comment by dingp** [comment]
This is now in `/cvmfs/dune.opensicengrid.org/dunedaq/DUNE/sandbox/nightly`. Once the nightly release becomes mature, we can move it out of the `sandbox` directory; or alternatively, request a `dune-development.opensciencegrid.org` cvmfs repo, as does so by other experiments for their development/nightly release.
