### ISSUE TITLE
Creating `sandbox` directory in cvmfs for prototyping features

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#45]
Creating `sandbox` directory in cvmfs for prototyping features, and move `pip-mirror`, `products-tmp` to it.

### pip-mirror 

`/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/pip-mirror` will be `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/sandbox/pip-mirror`. It is for our copies of python modules (from `pypi` and GitHub needed by the DAQ release.

### products-tmp (for CentOS 8)
`/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products-tmp` will be `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/sandbox/products-tmp`. It is currently hosting UPS products built for CentOS8.

### nightly releases

There will be a `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/sandbox/nightly` directory, which will be moved of the sandbox directory (by one level up in the dir tree) once it's mature.

The directory will have `mon, tue, wed, thu, fri` sub-dirs to host nightly releases, and have a `dunedaq-develop` linked to the last successfully built release.

**Comment by dingp** [comment]
With the `sandbox` directory created, the DUNE DAQ cvmfs repo will look like:

## Top level directories: `products  products_dev  releases  sandbox`

1. `products` for all UPS products (system, external, DAQ packages) and their versions;
2. `products_dev` for extra packages developers needed when working on new features, they are yet to be included in the official DAQ release;
3. `releases` for all frozen DAQ releases;
4. `sandbox` for prototyping new features of DAQ release/products setup (more details below).

## `sandbox` for prototyping features in cvmfs

1. `pip-mirror` for hosing our copies of python modules (for `pypi` or `GitHub`);
2. `products-tmp` for building externals or DAQ packages in other variants (different platform or build flavor), currently it contains the UPS products built for CentOS 8);
3. `products` is a symbolic link to the top level `products` directory, this is a hack to enable softlinks in the nightly release working before/after moving itself out of `sandbox`;
4. `nightly` is the directory hosting nightly-built release.. 

## `nightly` for nightly releases

1. `mon, tue, wed, thu, fri` for each nightly-built release;
2. `last_successful` links to the latest successfully-built nightly release. (#41)

**Comment by alessandrothea** [comment]
Thanks for writing up the plan, PengFei. It generally looks good. I have a couple of comments, but I would wrap up our discussion on slack about the CVMFS space footprint first.

I see two scenarios in front of us
- CVMFS space is limited, with small chances to request for an early flush if we run out of it. In this case, only production-grade "projects" should be uploaded. That means basically means that prototypes/releases/etc should be always be reviewed  
 before any upload to CVMFS is done.
- CVMFS space is limited but manageable. In this case, a staging area (`sandbox`) for new developments is highly desirable from my perspective to separate without any doubt production from prototypes.

Do we agree on this summary? And that there is sufficient maneuvering space in CVMFS to allow ourselves the staging area?
If not then we should stop here and agree on the way forward. 

Regarding the proposed CVMFS organization (I'm responding under the assumption we agree to go for `sandbox`):
- `pip-mirror` is kind of a misnomer. `pip` is the tool to install python packages from python package index (`pypi`) repositories. `pypi-repo` would seem more appropriate, or something similar.
- `products` is it really needed? 
- `products_dev`: if a link to `products` is necessary, a link to `products_dev` will be as well.
- `produtcs-tmp`: I find the `-tmp` kind of confusing. Would the softlink not be needed, I would have opted simply for `products`
- `nightly`: looks good

**Comment by dingp** [comment]
I think cvmfs space is manageable at the moment (it has not been an issue for the past >5 years at Fermilab). So the `sandbox` approach is doable. Though it is not guaranteed so in the future. The worst case is we loose `sandbox` and we fall back to the first approach you listed. That has a very low impact to our workflow since `sandbox` is meant to be a staging area and we can afford to loose it.


`pypi-repo` is a better name than `pip-mirror`. I'll change it.

Link to `products` is convenient to have, so that once things are ready in `sandbox`, they can be moved out of it directly without worrying about breaking soft links. Otherwise, the move will not be a literal `mv`, but recreating the actual contents (in our case, many soft links to the UPS products pool).

`products_dev` is not needed at the moment. That is simply because I have not included any DAQ packages needing things from it yet. I will create the link too if we agree on having these two links.

`products-tmp` was created a while ago but just moved to the `sandbox` area. Would `products-variant` be a better name since it was meant for experimenting with other build types (`debug` or other OS build).

**Comment by dingp** [comment]
New cvmfs repo layout with `sandbox` has been published.
