### ISSUE TITLE
Creating logging v1.0.0 UPS product for the next release

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-release#46]
The package [logging](https://github.com/DUNE-DAQ/logging) is to be included in the future DAQ release. To help developers with the transition from `ers` to `logging`, I built `v1.0.0` and deployed it in cvmfs under `products`.

```sh
/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products/logging/
```

To use it, firstly add `/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products` to `dune_products_dirs` in `dbt-settings` file, and then run `dbt-setup-build-environement` followed by `setup logging -q e19:prof`.

**Comment by alessandrothea** [comment]
I am sorry, where is this coming from? We have said a number of times that packages are added to `products` only at the time of the release. Until then developers are supposed to check out a local copy in their development areas. @dingp Please remove logging v1.0.0 from cvmfs.

**Comment by dingp** [comment]
Sorry, should have put it under `products_dev` area. The package has been moved there.

`products_dev` area is not set up by default (nor the products) area, and developers need to set up `logging v1.0.0` explicitly if they want to use it from cvmfs. So I see no harm for it being in cvmfs.

The following commands are for removing it from cvmfs if you prefer:

```sh
ssh cvmfsdune@oasiscfs02.fnal.gov # From a Fermilab machine
cvmfs_server transaction dune.opensciencegrid.org
rm -rf /cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/products_dev/logging
cvmfs_server publish dune.opensciencegrid.org
```

**Comment by alessandrothea** [comment]
Done!
