### ISSUE TITLE
Add official documentation for users to the new DUNE-DAQ software documentation site

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#61]
For the dunedaq-v2.4.1 release, please provide official documentation for this package's users as
described in
https://dune-daq-sw.readthedocs.io/en/latest/editing_package_documentation/.

**Comment by dingp** [comment]
Done.

Package `README.md` has been placed under `doc`.

I also added a link to that page is in the `README.md` under packages's root directory.
