### ISSUE TITLE
Add python modules for release dunedaq-v2.6

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-release#67]
Given that nanorc is commonly used for development and testing, the following python modules should be added to `pyvenv_requirements.txt`:
- [x] `click-shell==2.0`
- [x] `click-didyoumean=0.0.3`
- [x] `sh==1.14.1`
- [x] `graphviz==0.16`
- [x] `rich==10.2.2`

**Comment by strilov** [comment]
Hi. Can we also add `click-didyoumean`? It's needed by the timing python tools.

**Comment by dingp** [comment]
There modules have been added to `dunedaq-v2.6.0`, as well as `dunedaq-develop`.
