### ISSUE TITLE
Missing `cetpkgsupport` dependency in upsified DAQ packages

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-release#73]
This isn't really a bug, since it will never show up in the normal working of DAQ work areas etc, but I noticed that the upsified DAQ packages are missing a dependency on `cetpkgsupport`, so you can't `setup` them independently. Example:

```
> . /cvmfs/dunedaq.opensciencegrid.org/products/setups
> setup appfwk v2_3_1 -q e19:prof
bash: get-directory-name: command not found...
/cvmfs/dunedaq.opensciencegrid.org/products/appfwk/v2_3_1/.e19.prof directory not found: SETUP ABORTED
```

`get-directory-name` appears to be provided by `cetpkgsupport`. If you `setup` it first (as `dbt-workarea-env` does), then the `setup` of the DAQ package succeeds:

```
> setup cetpkgsupport v1_14_01
> setup appfwk v2_3_1 -q e19:prof
```

**Comment by dingp** [comment]
@philiprodrigues Thanks! This dependency was brought in by the UPS table files. I will add the dependency for future upsified packages.
