### ISSUE TITLE
add python connector for PostgreSQL

### ISSUE THREAD

**Issue by yadonon** [DUNE-DAQ/daq-release#74]
The added DQM features in 2.8 require python to access a PostgreSQL database.

The connector used is so far Psycopg2, which is the most popular python-Posgre connector, fast and secure. The following is needed:
```
bson             0.5.10
kafka-python     2.0.2
psycopg2         2.7.7
psycopg2-binary  2.9.1
python-dateutil  2.8.2
```

**Comment by alessandrothea** [comment]
Hi Yann. What part of the DQM requires these packages?

**Comment by yadonon** [comment]
Hi Alessandro, 

It is for the analysis micro-services.

I updated the list with all the modules needed, there was a small misunderstanding before. Let me know if you need more precision.

**Comment by alessandrothea** [comment]
Hi Yann,
Thanks, understood. I admit I don't know enough about the architecture you're putting in place to tell whether we should keep these packages in the same pot as the daq application software ones, or in a separate one.
Discussion needed, later this week or early next week, most likely if it's OK with you.
Alessandro

**Comment by yadonon** [comment]
Hi Alessandro,

Indeed, it would be good to have a talk about it, ultimately, I think they’ll do good away from the daq application “pot”. 
I’m available anytime, let me know how it suits you best. I believe I got a solution for 2.8 anyway.

Cheers
Yann

**Comment by dingp** [comment]
"Those packages can for now remain in a separate pot as suggested Alessandro." --Yann.
