### ISSUE TITLE
Bump version of cpr for next release from 1.5.2 to 1.6.2

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#75]
Requested by Yann in a Slack message on July 19:

"We had a talk with Giovanna this morning, cpr v1.5.2 caused a crash in some components here and updating it to 1.6.2 solved the issue. We would have liked to investigate the possibilities to update it also in the DAQ dependencies before the issues occurs here to, would that be possible for 2.8? "

**Comment by dingp** [comment]
New version 1.6.2 has been created and published to cvmfs. @yadonon Could you please give it a try?

**Comment by jcfreeman2** [comment]
I made the mistake of not closing this issue out, Yann told me on Tuesday that in fact cpr 1.6.2 wasn't the cause of the crash and he was fine without the version bump.
