### ISSUE TITLE
A lot of cut-and-pasted code could be consolidated (post dunedaq-v2.8.0)

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-release#77]
Something I discussed briefly with Pengfei this morning. I notice that there are functions which are cut-and-pasted across the `scripts/ups_build_scripts/*/*/build_*.sh` scripts. E.g., if we look at `scripts/ups_build_scripts/cpr/v1_5_2`:
```

# -------------------------------------------------------------------                                                                
# shared boilerplate                                                                                                                 
# -------------------------------------------------------------------                                                                

get_this_dir()
{
    ( cd / ; /bin/pwd -P ) >/dev/null 2>&1
    if (( $? == 0 )); then
      pwd_P_arg="-P"
    fi
    reldir=`dirname ${0}`
    thisdir=`cd ${reldir} && /bin/pwd ${pwd_P_arg}`
}

get_ssibuildshims()
{
    # make sure we can use the setup alias                                                                                           
    if [ -z ${UPS_DIR} ]
    then
       echo "ERROR: please setup ups"
       exit 1
    fi
    source `${UPS_DIR}/bin/ups setup ${SETUP_UPS}`

    setup ssibuildshims ${ssibuildshims_version} -z ${product_dir}:${PRODUCTS}
}

function setup_and_verify()
{
    # this should not complain                                                                                                       
    echo "Finished building ${package} ${pkgver}"
    setup ${package} ${pkgver} -q ${fullqual} -z ${product_dir}:${PRODUCTS}
    echo "${package} is installed at ${UHAL_FQ_DIR}"
}
```
...these three functions are seen in all build scripts, basically. And in fact you can see the effects of the cut-and-paste in that `UHAL_FQ_DIR` is echoed despite this being the build script for cpr. It would be nice if we created something like a `daq-release-tools.sh` file which would contain functions we'd want common to various build scripts.

**Comment by dingp** [comment]
The reason for the cut-and-paste sections of code is to enable each of the build script to have minimal dependency on others. And each of the subdirectories for a given package is self-contained. 

This follows the same fashion as SciSoft does for the build scripts in various source packages.
