### ISSUE TITLE
Prepare for dunedaq-v2.7.0

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-release#81]
1. Update python packages:
   - [x] Add `python-ipmi` (issue from stoyan) 
1. Deploy new version of `daq-buildtools` on CVMFS:
   - [x] created symbolic link (dunedaq-v2.7.0) to `v4.0.0`;
1. Build the release:
   - [x] create `dunedaq-v2.7.0` config directory;
   - [x] update `pyvenv_requirements.txt`;
   - [x] update `dbt-settting.sh`;
   - [x] update `release_manifest.sh`;
   - [x] build and deploy the releases to cvmfs;
1. Update documentation:
   - [ ] update documentation;
1. Make release tag
   - [x]  Tag packages included in this release with release tag `dunedaq-v2.6.0`.

List of DAQ packages and versions for this release:

| repo                | tag        |
| ------------------- | ---------- |
| `daq-buildtools`    | `v3.0.2`   |
| `daq-cmake`         | `v1.4.2`   |
| `ers`               | `v1.1.2c` (advance UPS product version to `v1.1.2b` since `v1.1.2` has been made with an older `ers` version)    |
| `erses`           | `v1.0.0` |
| `logging`           | `v1.0.2`  |
| `cmdlib`            | `v1.1.2c`   |
| `restcmd`           | `v1.1.2c`   |
| `opmonlib`          | `v1.3.0`   |
| `rcif`              | `v1.1.0b` (advance UPS product version to `v1.1.0b`)  |
| `appfwk`            | `v2.3.1`   |
| `listrev`           | `v2.1.3b` |

**Comment by jcfreeman2** [comment]
Updating the list of packages with the tags from https://docs.google.com/spreadsheets/d/1A-r7gVCYf5yGpxJDVfnEArpu8zibig3UJoTlNF-q7uI

repo | tag
-- | --
daq-buildtools | v4.0.0
daq-cmake | v2.0.0
ers | v1.1.3
erses | v1.0.0 
logging | v1.0.3
cmdlib | v1.1.4
restcmd | v1.1.3
opmonlib | v1.3.1
rcif | v1.1.1
appfwk | v2.3.2
listrev | v2.1.4
