### ISSUE TITLE
Add cvmfs management/ci build scripts to the repo

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-release#85]
## CVMFS
* `dunedaq-sync`
* `dunedaq-sync-delete`
* `dunedaq-sync-delete-dir`
* `dunedaq-sync-products`

## Nightlies
* `build-ci-docker.sh`
* `build-release.sh` ?
* `create-image.sh` ?
* `create-nightly-tarball.sh`

**Comment by dingp** [comment]
The nightlies script had been put into the `daq-docker` repo previously. Those seem to be more relevant here though (especially when we move to Gitlab or self-hosted GitHub where docker images are no longer needed).
