### ISSUE TITLE
Prepare for release dunedaq-v2.8.0

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-release#86]
1. Update python packages:
   - [x] Update `nanorc v1.3.1`
   - [x] Update `integrationtest` to `v1.2.0`;
1. Tools on CVMFS:
   - [x] created symbolic link (dunedaq-v2.8.0) to `v4.0.0`;
1. Build the release:
   - [x] create `dunedaq-v2.8.0` config directory;
   - [x] update `pyvenv_requirements.txt`;
   - [x] update `dbt-settting.sh`;
   - [x] update `release_manifest.sh`;
   - [x] modify `daq-develop` configs with similar updates as in this release;
   - [x] checkout DAQ packages and create local minor version tags for packages with re-used tags from previous releases (to distinguish build variants of UPS packages);
   - [x] update `release_manifest.sh` and `dbt-settings.sh` with minor version tags for packages with re-used tags;
   - [x] build and deploy the releases to cvmfs;
1. Update documentation:
   - [x] update documentation;
   - [x] verify CI workflow in `docs` repo (workflow is triggered every 15 minutes);
1. Make release tag
   - [ ]  Tag packages included in this release with release tag `dunedaq-v2.8.0`.
1. Documentation
   - ~tag `docs` repo with `dunedaq-v2.8.0` tag; 
List of DAQ packages and versions for this release:

|        repo       |   tag    |
|-------------------|----------|
| `daq-buildtools`  | `v4.0.0` |
| `daq-cmake`       | `v2.0.0` |
| `ers`             | `v1.1.3` |
| `logging`         | `v1.0.3` |
| `cmdlib`          | `v1.1.4` |
| `restcmd`         | `v1.1.3` |
| `opmonlib`        | `v1.3.2` |
| `rcif`            | `v1.1.1` |
| `appfwk`          | `v2.3.2` |
| `listrev`         | `v2.1.4` |
|-------------------|----------|
| `erses`           | `v1.0.0` |
| `erskafka`        | `v1.3.0` |
| `kafkaopmon`      | `v1.3.0` |
| `influxopmon`     | `v1.4.0` |
| `ipm`             | `v2.2.0` |
| `serialization`   | `v1.2.2` |
| `dfmessages`      | `v2.2.0` |
| `dataformats`     | `v3.0.0` |
| `readout`         | `v1.4.2` |
| `dfmodules`       | `v2.2.1` |
| `flxlibs`         | `v1.2.1` |
| `lbrulibs`        | `v1.0.3` |
| `nwqueueadapters` | `v1.4.0` |
| `timing`          | `v5.5.1` |
| `timinglibs`      | `v1.2.0` |
| `trigemu`         | `v2.3.0` |
| `minidaqapp`      | `v4.0.0` |
| `trigger`         | `v1.1.2` |
| `triggeralgs`     | `v0.3.0` |
| `dqm`             | `v1.0.0` |
| `integrationtest` | `v1.2.0` |
| `nanoRC`          | `v1.3.1` |

**Comment by dingp** [comment]
Patching the release with the following new versions of packages:

1. `trigger` `v1.1.2`; 
2. `dfmodules` `v2.2.1`;
3. `timing` `v5.5.1`.

**Comment by dingp** [comment]
Another patch with `readout` `v1.4.2`.
