### ISSUE TITLE
Upsificator workflow falls over for composite tags (e.g. relval/v1.2.3/b0) 

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-release#87]
I think the problem can be traced back when the git hash is reverse-parsed.
The script doing so doesn't cope well with `/` in the tag name.

**Comment by dingp** [comment]
The problem happens when the HEAD of develop has a special tag points to it (with `/` in the tag). A work-around is to create a minor version tag for that in the form of `vX.X.X`. 

However, I am adding more robust checks in the script, to take only the `vX.X.X` tag.
