### ISSUE TITLE
UHAL test apps in PATH

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/daq-release#93]
Hello,

Recently I accidentally ran:
`/cvmfs/dunedaq.opensciencegrid.org/products/uhal/v2_8_1/Linux64bit+3.10-2.17-e19-prof/bin/test_log.exe`

as it was put into PATH by `dbt-workarea-env`. I didn't do any output, and honestly freaked out for a second what is it and what it's doing/did it do.

The behavior is perfectly normal, but I'm wondering if we want to have a more rigorous policy what goes into PATH from the external dependencies.

**Comment by dingp** [comment]
Unfortunately, UPS does not regulate which goes to the `PATH`.  By default, it will add `pkg_install_path/bin` to the PATH env. 

What we can do here is specifying which executables goes to the `pkg_install_path/bin` when making the UPS product.
