### ISSUE TITLE
Include REGMAP_VERSION definition in felix cmake scripts

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daq-release#94]
The felix regmap package uses `REGMAP_VERSION` to determine what regmap version to include (no comments).
`REGMAP_VERSION` is correctly set to `0x0500` in the `felix` build script.
It's not set in the cmake files included in the ups package instead, which causes dependant packages to default to regmap4, which is likely to cause problems sooner or later.
It should be added there with value `0x0500`

**Comment by alessandrothea** [comment]
IT doesn't look like it's happening soon. Can you proceed with the existing version, please?

**Comment by dingp** [comment]
Sure. Doing it now.

**Comment by dingp** [comment]
The change has been pushed to cvmfs. The ENV should be available after setting up current version of Felix UPS product.
